//
//  History.swift
//  Yippy
//
//  Created by Matthew Davidson on 16/10/19.
//  Copyright © 2019 MatthewDavidson. All rights reserved.
//

import Foundation
import Cocoa
import RxSwift
import RxRelay

/// Representation of all the history
class History {
    
    private var _items = [HistoryItem]()
    
    /// Behaviour relay for the last change count of the pasteboard.
    /// Private so that it cannot be manipulated outside of the class.
    private var _lastRecordedChangeCount = BehaviorRelay<Int>(value: -1)
    
    /// Observable for the last recorded change count of the pasteboard.
    var observableLastRecordedChangeCount: Observable<Int> {
        return _lastRecordedChangeCount.asObservable()
    }
    
    /// The last change count for which the items on the pasteboard have been added to the history.
    var lastRecordedChangeCount: Int {
        return _lastRecordedChangeCount.value
    }
    
    /// The file manager for the storage of pasteboard history.
    var historyFM: HistoryFileManager
    
    /// The cache for the history item.
    var cache: HistoryCache
    
    private var _maxItems: BehaviorRelay<Int>
    
    var items: [HistoryItem] {
        get {
            return self._items
        }
    }
    
    var maxItems: Observable<Int> {
        _maxItems.asObservable()
    }
    
    enum Change {
        case initial
        case insert(index: Int)
        case delete(deletedItem: HistoryItem)
        case clear
        case move(from: Int, to: Int)
        case itemLimitDecreased(deletedItems: [HistoryItem])
    }
    
    /// Cheap fingerprints of item contents by id, for finding duplicates. Filled lazily by `fingerprint(of:)`.
    private var fingerprints = [UUID: Int]()
    
    typealias SubscribeHandler = ([HistoryItem], Change) -> Void
    private var subscribers = [SubscribeHandler]()
    
    /// Copies made while one of these apps is frontmost are not saved.
    var ignoredBundleIds = Set<String>()
    /// If a pasteboard item's types contains any of these, it will not be saved.
    private let pasteboardTypeDenylist: Set = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "com.typeit4me.clipping",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
        "net.antelle.keeweb",
    ]
    /// These pasteboard item types will not be saved.
    private let pasteboardTypeIgnoreList = Set([
        "dyn.ah62d4rv4gu8zg55zsmv0nvperf4g86varvu0635zqfx0nkdsqf00nkduqf31k3pcr7u1e3basv61a3k",
        // Yippy's own item id, written alongside every item it pastes (e.g. from favourites)
        HistoryItem.historyItemIdType.rawValue,
    ].map({NSPasteboard.PasteboardType(rawValue: $0)}));
    
    init(historyFM: HistoryFileManager = .default, cache: HistoryCache, items: [HistoryItem], maxItems: Int = Constants.system.maxHistoryItems) {
        self.historyFM = historyFM
        self.cache = cache
        self._items = items
        self._maxItems = BehaviorRelay<Int>(value: maxItems)
        
        if items.count > maxItems {
            reduceHistory(to: maxItems)
        }
    }
    
    static func load(historyFM: HistoryFileManager = .default, cache: HistoryCache) -> History {
        return historyFM.loadHistory(cache: cache)
    }
    
    func subscribe(onNext: @escaping SubscribeHandler) {
        subscribers.append(onNext)
        onNext(_items, Change.initial)
    }
    
    func insertItem(_ item: HistoryItem, at i: Int) {
        _items.insert(item, at: i)
        subscribers.forEach({$0(_items, Change.insert(index: i))})
        historyFM.insertItem(newHistory: _items, at: i)
        
        if _items.count > _maxItems.value {
            let deletedItem = _items[_items.count - 1]
            deleteItem(at: _items.count - 1)
            subscribers.forEach({$0(_items, Change.delete(deletedItem: deletedItem))})
        }
    }
    
    func deleteItem(at i: Int) {
        let removed = _items.remove(at: i)
        fingerprints.removeValue(forKey: removed.fsId)
        subscribers.forEach({$0(_items, Change.delete(deletedItem: removed))})
        historyFM.deleteItem(newHistory: _items, deleted: removed)
    }
    
    func clear() {
        _items.forEach({$0.stopCaching()})
        _items = []
        fingerprints = [:]
        subscribers.forEach({$0(_items, Change.clear)})
        historyFM.clearHistory()
    }
    
    func moveItem(at i: Int, to j: Int) {
        let item = _items.remove(at: i)
        _items.insert(item, at: j)
        subscribers.forEach({$0(_items, Change.move(from: i, to: j))})
        historyFM.moveItem(newHistory: _items, from: i, to: j)
    }
    
    func recordPasteboardChange(withCount changeCount: Int) {
        _lastRecordedChangeCount.accept(changeCount)
    }
    
    func setMaxItems(_ maxItems: Int) {
        if maxItems < _maxItems.value {
            reduceHistory(to: maxItems)
        }
        _maxItems.accept(maxItems)
    }
    
    private func reduceHistory(to maxItems: Int) {
        guard _items.count > maxItems else {
            return;
        }
        historyFM.reduce(oldHistory: _items, toSize: maxItems)
        let deletedItems = Array(_items.suffix(_items.count - maxItems))
        _items = Array(_items.prefix(maxItems))
        deletedItems.forEach({ fingerprints.removeValue(forKey: $0.fsId) })
        subscribers.forEach({$0(_items, Change.itemLimitDecreased(deletedItems: deletedItems))})
    }
}

// MARK: - Duplicates
extension History {
    
    /// Hashes the types and data. `Data`'s own hash only looks at a prefix of the bytes, so equal fingerprints still need a full comparison.
    static func fingerprint(of data: [NSPasteboard.PasteboardType: Data]) -> Int {
        var hasher = Hasher()
        for type in data.keys.sorted(by: { $0.rawValue < $1.rawValue }) {
            hasher.combine(type)
            hasher.combine(data[type]!.count)
            hasher.combine(data[type]!)
        }
        return hasher.finalize()
    }
    
    /// The item's fingerprint, reading its data the first time. Nil if some of its data can't be read.
    private func fingerprint(of item: HistoryItem) -> Int? {
        if let f = fingerprints[item.fsId] {
            return f
        }
        guard let data = allData(of: item) else {
            return nil
        }
        let f = Self.fingerprint(of: data)
        fingerprints[item.fsId] = f
        return f
    }
    
    private func allData(of item: HistoryItem) -> [NSPasteboard.PasteboardType: Data]? {
        var data = [NSPasteboard.PasteboardType: Data]()
        for type in item.types {
            guard let d = item.data(forType: type) else {
                return nil
            }
            data[type] = d
        }
        return data
    }
    
    /// Index of the item with exactly these types and data, if there is one.
    func indexOfItem(withData data: [NSPasteboard.PasteboardType: Data]) -> Int? {
        let types = Set(data.keys)
        let f = Self.fingerprint(of: data)
        return _items.firstIndex(where: {
            Set($0.types) == types
                && fingerprint(of: $0) == f
                && allData(of: $0) == data
        })
    }
}

extension History: PasteboardMonitorDelegate {
    
    func pasteboardDidChange(_ pasteboard: NSPasteboard, originBundleId: String?) {
        // Check if we made this pasteboard change, if so, ignore
        if pasteboard.changeCount == lastRecordedChangeCount {
            return
        }
        
        // Skip copies from ignored apps, but still record the change so it isn't picked up later
        if let originBundleId = originBundleId, ignoredBundleIds.contains(originBundleId) {
            recordPasteboardChange(withCount: pasteboard.changeCount)
            return
        }
        
        // Check there are items on the pasteboard
        guard let items = pasteboard.pasteboardItems else {
            return
        }
        
        for item in items {
            let filteredTypes = Set(item.types).subtracting(self.pasteboardTypeIgnoreList)
            let hasTypes = !filteredTypes.isEmpty
            let hasNoDeniedTypes = Set(filteredTypes.map({ $0.rawValue })).isDisjoint(with: pasteboardTypeDenylist)
            
            if hasTypes && hasNoDeniedTypes {
                var data = [NSPasteboard.PasteboardType: Data]()
                for type in filteredTypes {
                    if let d = item.data(forType: type) {
                        data[type] = d
                    }
                    else {
                        print("Warning: new pasteboard data nil for type '\(type.rawValue)'")
                    }
                }
                if data.isEmpty {
                    continue
                }
                
                // Copying something already in the history brings it back to the top instead of adding it again
                if let i = indexOfItem(withData: data) {
                    if i != 0 {
                        moveItem(at: i, to: 0)
                    }
                }
                else {
                    let historyItem = HistoryItem(unsavedData: data, cache: cache)
                    fingerprints[historyItem.fsId] = Self.fingerprint(of: data)
                    insertItem(historyItem, at: 0)
                }
            }
        }
        
        // Save pasteboard change count
        recordPasteboardChange(withCount: pasteboard.changeCount)
    }
}
